
spring:
  application:
    name: CDWeb
  datasource:
    url: jdbc:mysql://localhost:3306/CDWeb
    username: root
    password: tatksvesport2003
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
jwt:
  signerKey: "uCkfHIKvRUqCFCOkH03RXF99oOVJuMjohs2tD1/xmlWQZikBw8kWu2eXzrib7/hl"

server:
  port: 8080
  servlet:
    context-path: /